// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOKiWbR1qWG-kFynWy7g0ip599IMq5lBU',
    appId: '1:556578707174:web:8424674507a37746fccd27',
    messagingSenderId: '556578707174',
    projectId: 'pocketplan-3926e',
    authDomain: 'pocketplan-3926e.firebaseapp.com',
    storageBucket: 'pocketplan-3926e.firebasestorage.app',
    measurementId: 'G-3KDQPW1R2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYRDZZWySa2NoOjer5HrS1CBzKIO9hKk',
    appId: '1:556578707174:android:da7c98b8ead2843dfccd27',
    messagingSenderId: '556578707174',
    projectId: 'pocketplan-3926e',
    storageBucket: 'pocketplan-3926e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbde0OhjUr0ZMW4xvxL8h46EsX88OsGFg',
    appId: '1:556578707174:ios:75a10955fc20c1fffccd27',
    messagingSenderId: '556578707174',
    projectId: 'pocketplan-3926e',
    storageBucket: 'pocketplan-3926e.firebasestorage.app',
    iosBundleId: 'com.example.pocketPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbde0OhjUr0ZMW4xvxL8h46EsX88OsGFg',
    appId: '1:556578707174:ios:75a10955fc20c1fffccd27',
    messagingSenderId: '556578707174',
    projectId: 'pocketplan-3926e',
    storageBucket: 'pocketplan-3926e.firebasestorage.app',
    iosBundleId: 'com.example.pocketPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOKiWbR1qWG-kFynWy7g0ip599IMq5lBU',
    appId: '1:556578707174:web:37ef98069e8a55c0fccd27',
    messagingSenderId: '556578707174',
    projectId: 'pocketplan-3926e',
    authDomain: 'pocketplan-3926e.firebaseapp.com',
    storageBucket: 'pocketplan-3926e.firebasestorage.app',
    measurementId: 'G-5KEJ6S7J61',
  );

}